Update all dev endpoints to use https and wss
dydxprotocol/v4-web pull request #117
Opened 2023-11-03 21:00 UTC by Christopher-Li

Update all dev endpoints to use https and wss
---

## Views

* New: `<ViewComponentName>`
  * 
  * 

* `<ViewComponentName>`
  * 
  * New: ``
  * Rename: `` → ``
  * 

## Components

* New: `<ComponentName>`
  * 
  * 

* `<ComponentName>`
  * 
  * New: ``
  * Rename: `` → ``
  * 

## Styles/Mixins

* `styles/_____`
  * 
  * New: ``
  * Rename: `` → ``
  * 

## Constants/Types

* `constants/_____`
  * 
  * 

## Functions

* `lib/_____`
  * 
  * 

## Hooks

* `hooks/_____`
  * 
  * 

## State

* `state/_____`
  * 
  * 

## Packages

* `package-name`
  * 
  * updated: v__ -> v__

## Workflows

* `workflow-name.yml`
  * 
  * 

---

2023-11-03 21:10 UTC, aforaleka approved these changes

2023-11-04 23:11 UTC, jaredvu requested changes
dev2 and dev5 don't have https/wss

2023-11-06 17:33 UTC, jaredvu approved these changes

2023-11-06 17:33 UTC, jaredvu approved these changes

2023-11-06 17:33 UTC, merged