Fix inputs for comma locales
dydxprotocol/v4-web pull request #171
Opened 2023-11-29 09:43 UTC by jaredvu

https://github.com/dydxprotocol/v4-web/assets/13111994/ff5f554f-ee01-47b8-a511-f3b5aa1c99b4

Allow users with a locale that uses `,` as their decimal separator to properly input.

---

## Views

* `<TradeForm>`
  * Use nullish coalescing operator instead of `||` to support a `tickSizeDecimal` of `0`.

## Components

* `<Input>`
  * Use conditional props to separate props that are only applicable to a subset of `InputTypes`
  * Add `valueIsNumericString` prop to fix issue of (`,` decimal separator resetting the value)

## Hooks

* `hooks/useTradeFormInputs.ts`
  * remove `parseFloat` usage. Abacus handles the `string` parsing

---

2023-11-29 18:01 UTC, rosepuppy approved these changes

2023-11-29 18:39 UTC, rosepuppy requested changes
actually the size inputs are not fixed yet. I can help take a look later

2023-12-01 14:48 UTC, jaredvu commented
> actually the size inputs are not fixed yet. I can help take a look later

The size inputs for the the tradeForm, DepositForm, WithdrawForm, and TransferFrom all accept the current locale's decimal separator.

https://github.com/dydxprotocol/v4-web/assets/13111994/98668fdf-06dc-4681-9211-cc049fb5a6e7

2023-12-05 00:44 UTC, rosepuppy approved these changes

2023-12-06 00:22 UTC, merged